### ISSUE TITLE
BUG: DBM skin broke with Update v1.13.70-classic

### ISSUE THREAD

**Issue by Lamindra** [Wetxius/ShestakUI_Classic#6]
Timers are not skinned and produce lua errors.

Rollback to v1.13.69-classic fixes the issue.

According to the DBM-changelog they changed their skinning API:
https://github.com/DeadlyBossMods/DBM-Classic/releases/tag/1.13.70

**Comment by Wetxius** [comment]
I do not plan to update, please use the original version: https://github.com/EsreverWoW/ShestakUI_Classic
